replicaCount: 1

webapp:
  name: #APP_NAME
  group: #APP_NAME
  path: #URL_PATH
  tls:
    fqdn: #FQDN
    secretName: incommon-cert-#HOST
  container: 
    image: #IMAGE_NAME
    port: #CONTAINER_PORT
    memory: 1G
    cpu: 2